name = "brett-otel-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-30"

[dev]
port = 8877

[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[d1_databases]]
binding = "DB"
database_name = "DB_BRETT_01"
database_id = "d5690637-45ce-4902-ae38-09b9c01a8e5c"

[build]
command = "cargo install -q worker-build && worker-build --release"
watch_dir = [
    "src",
    "migrations",
    "Cargo.toml",
    "../otel-worker-core",
    "../otel-worker-macros",
    "../Cargo.toml",
    "../Cargo.lock",
]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]
